name: Build

# build on pushes to main, and any PRs to main
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

env:
  IMAGE_NAME: ghcr.io/sportstech/kratos

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        id: build
        run: |
          DOCKER_BUILDKIT=1 \
          DOCKER_CONTENT_TRUST=1 \
          docker build \
            --build-arg=COMMIT=${{ github.sha }} \
            --build-arg=BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
            --file .docker/Dockerfile-build \
            --tag ${{env.IMAGE_NAME}}:${{github.sha}} \
            .
      - name: Push Docker image
        if: github.event_name == 'push'
        run: docker tag ${{env.IMAGE_NAME}}:${{github.sha}} ${{env.IMAGE_NAME}}:${{github.ref_name}} && docker push -a ${{env.IMAGE_NAME}}
